package com.prutech.entity

import com.prutech.entity.TruckEvent;

declare TruckEvent
    @role( event )
end

rule "Violation"
    when
        $t : TruckEvent()
        $d : Number() from $t.driverId
        Number( $count : intValue, $count >= 1 ) from accumulate(
            $violations : TruckEvent(eventType != "Normal" && driverId == $d.intValue())
            over window:time(3m), count( $violations ))
    then
        System.out.println("Violation by driver " + $d);
end
